PROJETO FINAL/backend/contact-list/apps/contact/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path(r'^$', home, name='contact-home')
]

PROJETO FINAL/backend/contact-list/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('apps.contact.urls'), name='contact'),
]

PROJETO FINAL/backend/contact-list/apps/contact/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    phone = models.CharField(max_length=9, verbose_name='Phone')
    email = models.EmailField(verbose_name='Email')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

PROJETO FINAL/backend/contact-list/apps/contact/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'contact/login.html', {})

PROJETO FINAL/backend/contact-list/templates/base_templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Contact List - Projeto Final</title>

    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
    
    {% block css-extra %}
    {% endblock %}
</head>

<body>

    {% block header %}
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">
                <span class="oi oi-list"></span> CONTACT LIST</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="login.html">
                            <span class="oi oi-account-logout"></span> Sign up</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    {% endblock %}
    
    {% block main %}
    {% endblock %}
    
    {% block footer %}
    <footer class="footer">
        <div class="container">
            <span class="text-muted">&copy; Imersão 2018.1 - Fábrica de Software</span>
        </div>
    </footer>
    {% endblock %}
    
    {% block js %}
    {% endblock %}

</body>

</html>

PROJETO FINAL/backend/contact-list/templates/contact/edit_create.html
{% extends 'base_templates/base.html' %}
{% load staticfiles %}

{% block main %}
<main role="main" class="container">

    <div class="mt-5">
        <p>
            <a class="btn btn-lg btn-secondary" href="index.html" role="button">
                <span class="oi oi-media-step-backward"></span> VOLTAR</a>
        </p>
    </div>

    <hr>

    <div class="mt-5">
        <form method="post" action="">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="id_name">Name</label>
                    <input type="text" class="form-control" id="id_name" placeholder="" value="" required>
                </div>
                <div class="col-md-6 mb-3"></div>
                <div class="col-md-6 mb-3">
                    <label for="id_phone">Phone</label>
                    <input type="tel" class="form-control" id="id_phone" placeholder="">
                </div>
                <div class="col-md-6 mb-3"></div>
                <div class="col-md-6 mb-3">
                    <label for="id_email">Email</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="email" class="form-control" id="id_email" placeholder="you@example.com" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Your username is required.
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-3"></div>

            </div>

            <div class="mt-5">
                <p>
                    <a class="btn btn-lg btn-primary" href="edit_create.html" role="button">
                        <span class="oi oi-check"></span> SUBMIT</a>
                </p>
            </div>
        </form>
    </div>
</main>
{% endblock %}

PROJETO FINAL/backend/contact-list/templates/contact/index.html
{% extends 'base_templates/base.html' %}
{% load staticfiles %}

{% block css-extra %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap4.min.css">
{% endblock %}

{% block main %}
<main role="main" class="container">

  <div class="mt-5">
    <p>
      <a class="btn btn-lg btn-primary" href="edit_create.html" role="button">
        <span class="oi oi-plus"></span> NEW CONTACT</a>
    </p>
  </div>

  <hr>

  <div class="mt-5">
    <table id="table-contact" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Phone</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>(83) 9 9955-6677</td>
          <td>mark@email.com</td>
          <td>
            <a class="btn btn-sm btn-warning" href="edit_create.html" role="button">
              <span class="oi oi-pencil"></span>
            </a>
            <a class="btn btn-sm btn-danger" href="#" role="button">
              <span class="oi oi-trash"></span>
            </a>
          </td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>(83) 9 9955-6677</td>
          <td>jacob@email.com</td>
          <td>
            <a class="btn btn-sm btn-warning" href="edit_create.html" role="button">
              <span class="oi oi-pencil"></span>
            </a>
            <a class="btn btn-sm btn-danger" href="#" role="button">
              <span class="oi oi-trash"></span>
            </a>
          </td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>(83) 9 9955-6677</td>
          <td>larry@email.com</td>
          <td>
            <a class="btn btn-sm btn-warning" href="edit_create.html" role="button">
              <span class="oi oi-pencil"></span>
            </a>
            <a class="btn btn-sm btn-danger" href="#" role="button">
              <span class="oi oi-trash"></span>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap4.min.js"></script>

<script>
  $(document).ready(function () {
    $('#table-contact').DataTable({
      responsive: {
        details: {
          display: $.fn.dataTable.Responsive.display.modal({
            header: function (row) {
              var data = row.data();
              return 'Details for ' + data[0] + ' ' + data[1];
            }
          }),
          renderer: $.fn.dataTable.Responsive.renderer.tableAll({
            tableClass: 'table'
          })
        }
      }
    });
  });
</script> 
{% endblock %}

PROJETO FINAL/backend/contact-list/templates/contact/login.html
{% extends 'base_templates/base.html' %}
{% load staticfiles %}

{% block css-extra %}
<link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<form method="post" class="form-signin" action="index.html">
  <div class="text-center mb-4">
    <img class="mb-4" src="{% static 'img/list_contact.png' %}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Log in to Contact List</h1>
  </div>

  <div class="form-label-group">
    <input type="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
    <label for="inputUsername">Username</label>
  </div>

  <div class="form-label-group">
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
    <label for="inputPassword">Password</label>
  </div>

  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted text-center">&copy; Imersão 2018.1 - Fábrica de Software</p>
</form>
{% endblock %}

{% block footer %}
{% endblock %}